### ISSUE TITLE
Android Basics: Navigation backstack

### ISSUE THREAD

**Issue by sbswami** [google-developer-training/android-basics-kotlin-cupcake-app#37] opened 2021-09-23 06:27 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-navigation-backstack#4

**In which task and step of the codelab can this issue be found?**
In `Send the order` -> step 6.

**Describe the problem**
In `getQuantityString(R.string.cupcakes, 1, 1)` the resources id shouldn't be `R.string.cupcakes`, it should be `R. plurals.cupcakes`

**Comment by kkuan2011** [comment] 2021-10-25 23:07
Thank you! Duplicate of #16 and will be fixed.

**Closed as completed by kkuan2011** 2021-10-25 23:07 UTC
